export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: [
    "dashboard.view",
    "boat.view",
    "boat.create",
    "boat.edit",
    "boat.delete",
    "schedule.view",
    "schedule.create",
    "schedule.edit",
    "schedule.delete",
    "booking.view",
    "booking.update",
    "booking.cancel",
    "staff.view",
    "staff.create",
    "staff.edit",
    "staff.delete",
    "wallet.view",
    "wallet.manage",
    "payment.view",
    "payment.refund",
    "report.view",
    "notification.view",
    "profile.update",
    "authority.boat.verify",
    "authority.permit.approve",
    "authority.route.approve",
    "refund.view",
    "refund.verify",
    "refund.approveLevel1",
    "refund.viewAll",
    "refund.finalApprove",
    "refund.reject",
    "refund.process",
    "refund.override",
  ],
  BOAT_OWNER: [
    "dashboard.view",
    "boat.view",
    "boat.create",
    "boat.edit",
    "boat.delete",
    "schedule.view",
    "schedule.create",
    "schedule.edit",
    "schedule.delete",
    "booking.view",
    "booking.update",
    "booking.cancel",
    "staff.view",
    "staff.create",
    "staff.edit",
    "staff.delete",
    "payment.view",
    "payment.refund",
    "report.view",
    "notification.view",
    "profile.update",
  ],
  MANAGER: [
    "dashboard.view",
    "boat.view",
    "boat.create",
    "boat.edit",
    "boat.delete",
    "schedule.view",
    "schedule.create",
    "schedule.edit",
    "schedule.delete",
    "booking.view",
    "booking.update",
    "booking.cancel",
    "staff.view",
    "staff.create",
    "staff.edit",
    "staff.delete",
    "payment.view",
    "payment.refund",
    "report.view",
    "notification.view",
    "profile.update",
  ],
  DRIVER: [
    "dashboard.view",
    "boat.view",
    "booking.view",
    "notification.view",
    "profile.update",
  ],
  CAPTAIN: [
    "dashboard.view",
    "boat.view",
    "booking.view",
    "staff.view",
    "notification.view",
    "profile.update",
  ],
  HELPER: [
    "dashboard.view",
    "boat.view",
    "booking.view",
    "notification.view",
    "profile.update",
  ],
  CUSTOMER: [
    "dashboard.view",
    "booking.view",
    "booking.cancel",
    "wallet.view",
    "notification.view",
    "profile.update",
  ],
  CITY_AUTHORITY: [
    "dashboard.view",
    "authority.boat.verify",
    "authority.permit.approve",
    "authority.route.approve",
    "report.view",
    "notification.view",
    "profile.update",
    "refund.view",
    "refund.verify",
    "refund.approveLevel1",
  ],
};

export const getMergedPermissions = (role: string, permissions: string[] = []): string[] => {
  const defaults = DEFAULT_ROLE_PERMISSIONS[role] || [];
  return Array.from(new Set([...permissions, ...defaults]));
};
